apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: backendfeed 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backendfeed 
    spec:
      containers:
        - name: backendfeed 
          image: andrewklazinga.azurecr.io/backendfeed
          ports:
          - containerPort: 80