apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  selector:
    matchLabels:
      service: reverseproxy
  replicas: 1
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 25%
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
#      - image: andrewklazinga/reverseproxy             #used for Docker hub
      - image: andrewklazinga.azurecr.io/backend-user   #used for Azure Container Registry
        name: reverseproxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always
      ports:
        - containerPort: 8080
      readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1 