version: "3"
services:
  reverseproxy:
      image: andrewklazinga/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: andrewklazinga/udacity-c3-restapi-user
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRESS_USERNAME: udagramklazdev2
      POSTGRESS_PASSWORD: udagramklazdev2 
      POSTGRESS_DATABASE: udagramklazdev2
      POSTGRESS_HOST: udagramklazdev2.cpixcjgzxvdv.us-east-1.rds.amazonaws.com
      AWS_REGION: us-east-1
      AWS_PROFILE: default
      AWS_BUCKET: andy-udagram-klaz-dev
      JWT_SECRET: helloworld 
      URL: "http://localhost:8100"
  backend-feed:
    image: andrewklazinga/udacity-c3-restapi-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRESS_USERNAME: udagramklazdev2
      POSTGRESS_PASSWORD: udagramklazdev2 
      POSTGRESS_DATABASE: udagramklazdev2
      POSTGRESS_HOST: udagramklazdev2.cpixcjgzxvdv.us-east-1.rds.amazonaws.com
      AWS_REGION: us-east-1
      AWS_PROFILE: default
      AWS_BUCKET: andy-udagram-klaz-dev
      JWT_SECRET: helloworld 
      URL: "http://localhost:8100"
  frontend:
    image: andrewklazinga/udacity-c3-frontend
    ports:
      - "8100:80"
